config/routes.rb
Rails.application.routes.draw do

  # get 'reports/new'

  resources :reports

  # post 'reports/new'

  get 'welcome/index'

  devise_for :users
  
  get 'main_controller/index'

  resources :flats

  root 'main_controller#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
	has_many :users
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :flat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
	def new
	end

	def create
		@flat = Flat.new(params[:name])

		@flat = Flat.create(params.require(:flat).permit(:name))
		@flat.save
		redirect_to @flat
		#@user.flat = :id
	end

	def show
	    @flat = Flat.find(params[:id])
	end
end

app/controllers/main_controller_controller.rb
class MainControllerController < ApplicationController
  def index
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def main
  end

  def create
  		@problem = Problem.new(params[:item])


  		@problem = Problem.create(params.require(:problem).permit(:item))

  		@problem.save
  		redirect_to @problem
  end

  def show
  	@problem = Problem.find(params[:id])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
  end

  def create
  	@reports = Report.new(params[:item])

	@reports = Report.create(params.require(:report).permit(:item))
	@reports.save
	redirect_to @reports
	end

	def show
	    @items = Report.take(10)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/main_controller_helper.rb
module MainControllerHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flats/new.html.erb
<h1>Create your flat <br>
  (give it a nice name!)</h1>
  <%= form_for :flat, url: flats_path do |f| %>
    <p>
      <!-- <%= f.label :name %><br> -->
      <%= f.text_field :name %>
    </p>

     <p>
      <%= f.submit :class => 'btn btn-xs' %>
    </p>
<% end %>

app/views/flats/show.html.erb
<h1 id="welcome">
  Welcome,
</h1>
<br>
<h1 class="btn btn-s">
  <%= @flat.name %>
</h1>
<div class="cover"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flatm8</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if notice %>
  	  <p class="alert alert-success"><%= notice %></p>
  	<% end %>
  	<% if alert %>
  	  <p class="alert alert-danger"><%= alert %></p>
  	<% end %>
    <div class="top-bar"></div>
  	<p class="navbar-text pull-right">
  	<% if user_signed_in? %>
  	  Logged in as <strong><%= current_user.email %></strong>.
      <br>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  	<% else %>
  	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  	<% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main_controller/index.html.erb
<head>
  <title>
    flatm8
  </title>
</head>

<body>
  <div id="login">
    <h1>
      flatm8
    </h1>
    <h2>
      make your flat more productive
    </h2>
    <%= link_to "Create flat", new_flat_path, :class =>  "btn btn-l", :id => "btn-new-flat"%>
    <!-- <a href="/flats/new" id="btn-create" class="btn btn-l">
      Create flat
    </a> -->
    <%= link_to "Join flat", new_flat_path, :class =>  "btn btn-m", :id => "btn-join-flat"%>
    <!-- <a href="/flats/join" id="btn-join" class="btn btn-m">
      Join flat
    </a> -->
    <%= link_to "Login", new_user_session_path, :class =>  "btn btn-s", :id => "btn-sign-in"%>
    <!-- <a href="/users/sign_in" id="btn-sign-in" class="btn btn-s">
      Sign in
    </a> -->
  </div>
</body>

app/views/report/main.html.erb
<h1>report#main</h1>

<h4>Please raise your issue?</h4>

<%= form_for :problem, url: problems_path do |f| %>
  <p>
     <%= f.label :issue %><br>
     <%= f.text_field :issue %>
  </p>

   <p>
     <%= f.submit %>
   </p>
 <% end %>

app/views/report/show.html.erb
<p>
  <strong>Item:</strong>
  <%= @report.item %>
</p>

app/views/reports/new.html.erb
<h1>Reports</h1>

<%= form_for :report, url: reports_path do |f| %>
  <p>
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reports/show.html.erb
<p>
  <strong>Issue:</strong>
  <ul>
  <%= @items.each do |element| %>
  <li><%= element.item %></li>
  <% end %>
  </ul>
</p>